Configure tox
vintasoftware/django-celerybeat-status pull request #10
Opened 2018-02-06 16:11 UTC by hugobessa

Configures tox to test the project in multiple environments

The selected environments are: 
* {py27, py35, py36} django-110
* {py27, py35, py36} django-111
* {py35, py36} django-20

2018-02-15 20:04 UTC, chocoelho commented on .python-version
> +3.6.2
This is from your local pyenv environment. Add this to `.gitignore`

2018-02-15 20:08 UTC, chocoelho commented on celerybeat_status/tests/test_views.py
> +except ImportError:
I think that checking by versions is more elegant:

```python
from django.utils import version as django_version

if django_version.get_complete_version() < (2, 0, 0):
    from django.core.urlresolvers import reverse
else:
    from django.urls import reverse
```

2018-02-15 20:10 UTC, chocoelho requested changes
Please add local pyenv configuration to `.gitignore` and make use of version to check on from where to import a module instead of using exceptions. The latter is preferable since is way more readable on why you're trying the alternate import.

2018-02-16 05:14 UTC, hugobessa commented
Thank you for the review @chocoelho! I've fixed the points you mentioned

2018-02-16 11:31 UTC, chocoelho approved these changes

2018-02-16 11:46 UTC, merged